// 100 Sci-Fi Aliases for Random Name Generator
export const sciFiAliases: string[] = [
  'Ace',
  'Clutch',
  'Frag',
  'Carry',
  'Pivot',
  'Anchor',
  'Entry',
  'IGL',
  'Flex',
  'Support',
  'Duel',
  'Solo',
  'Focus',
  'Prime',
  'Elite',
  'Ultra',
  'Core',
  'Viper',
  'Phantom',
  'Reaper',
  'Rogue',
  'Sentinel',
  'Striker',
  'Sniper',
  'Rusher',
  'Hunter',
  'Predator',
  'Titan',
  'Apex',
  'Alpha',
  'Omega',
  'Zero',
  'Nova',
  'Zenith',
  'Pulse',
  'Volt',
  'Frost',
  'Blaze',
  'Storm',
  'Echo',
  'Shadow',
  'Spectre',
  'Cipher',
  'Vector',
  'Matrix',
  'Nexus',
  'Flux',
  'Glitch',
  'Overkill',
  'HardCarry',
  'OneTap',
  'Headshot',
  'Ult',
  'Cooldown',
  'Respawn',
  'Final',
  'Sudden',
  'Momentum',
  'Execute',
  'Tactical',
  'Precision',
  'Control',
  'Dominant',
  'Relentless',
  'Unbreakable'
];

/**
 * Get a random sci-fi alias from the list
 * @returns A random sci-fi name
 */
export function getRandomSciFiName(): string {
  const randomIndex = Math.floor(Math.random() * sciFiAliases.length);
  return sciFiAliases[randomIndex];
}
